### ISSUE TITLE
Some prerequisites of running pipeline in a local environment are missing

### ISSUE THREAD

**Issue by xuanyuwang** [elyra-ai/examples#34]
# Desription

When following the [Running pipelines in a local environment](https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world) tutorial to step [Running a notebook pipeline locally](https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world#running-a-notebook-pipeline-locally), a user may see the following error message:
![Screen Shot 2021-02-17 at 2 30 41 PM](https://user-images.githubusercontent.com/22479912/108257399-b7bc4200-712c-11eb-932a-450c5e64cd7a.png)

The error details is:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/elyra/pipeline/processor_local.py", line 191, in process
    papermill.execute_notebook(
  File "/usr/local/lib/python3.9/site-packages/papermill/execute.py", line 118, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/local/lib/python3.9/site-packages/papermill/execute.py", line 230, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-dd0d2a848dc3> in <module>
      1 # Define required imports
----> 2 import pandas as pd
      3 import numpy as np
      4 import sys
      5 import re

ModuleNotFoundError: No module named 'pandas'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/elyra/pipeline/processor_local.py", line 74, in process
    operation_processor.process(operation)
  File "/usr/local/lib/python3.9/site-packages/elyra/pipeline/processor_local.py", line 197, in process
    raise RuntimeError(f'Internal error executing {filepath}: {ex}') from ex
RuntimeError: Internal error executing /Users/xuanyu/examples/pipelines/hello_world/Part 1 - Data Cleaning.ipynb: 
---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-dd0d2a848dc3> in <module>
      1 # Define required imports
----> 2 import pandas as pd
      3 import numpy as np
      4 import sys
      5 import re

ModuleNotFoundError: No module named 'pandas'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/lib/python3.9/site-packages/elyra/pipeline/handlers.py", line 89, in post
    response = await PipelineProcessorManager.instance().process(pipeline)
  File "/usr/local/lib/python3.9/site-packages/elyra/pipeline/processor.py", line 70, in process
    res = await asyncio.get_event_loop().run_in_executor(None, processor.process, pipeline)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/elyra/pipeline/processor_local.py", line 79, in process
    raise RuntimeError(f'Error processing operation {operation.name}.') from ex
RuntimeError: Error processing operation Part 1 - Data Cleaning.
```

# Possible cause and a potential fix

The reason is that the package `pandas` was not installed. When we open the notebook `Part 1 - Data Cleaning.ipynt`, we'll see this screen:
![Screen Shot 2021-02-17 at 2 33 45 PM](https://user-images.githubusercontent.com/22479912/108257679-26010480-712d-11eb-8342-871828cb6ba6.png)

Installing `pandas` by running `pip3 install pandas` can resolve this problem.

## Suggestion

It is a small thing and can be easily fixed. However, I don't find anywhere in the documentation of installing Elyra or the documentation of Running pipelines in a local environment that says that `pandas` is one of the prerequites.

So, we may want to tell a user at [Prerequisites section](https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world#prerequisites) that they need to make sure that `pandas` along with other packages like `numpy` should be there before running the pipeline.

# Reproduce steps

Environment:
- macOS Big Sur. 
- Python 3.9.1

Steps:
1. install Elyra by running `pip install --upgrade "elyra>=2.0.1" && jupyter lab build`
2. following the tutorial: https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world#running-a-notebook-pipeline-locally.
3. make sure the Runtime Image is Pandas 1.1.1, just like the screenshot from the tutorial
4. run the pipeline

**Comment by karlaspuldaro** [comment]
Hi @xuanyuwang , thank you for opening this issue.
I think it's a good idea to let users know about `pandas` dependency in the hello world example [prerequisites](https://github.com/elyra-ai/examples/tree/master/pipelines/hello_world#prerequisites). 
@ptitzler ?

**Comment by ptitzler** [comment]
In general I agree. However, to keep things simple and portable the first cell in each tutorial notebook includes one or more `!pip install`, which should install the prerequisite packages in the kernel where the notebook is running. For example, in https://github.com/elyra-ai/examples/blob/master/pipelines/hello_world/Part%201%20-%20Data%20Cleaning.ipynb

![image](https://user-images.githubusercontent.com/13068832/108268476-6bb7d000-7121-11eb-81ce-15d03aba6c5f.png)

In what kind of environment are you running?

**Comment by xuanyuwang** [comment]
> In general I agree. However, to keep things simple and portable the first cell in each tutorial notebook includes one or more `!pip install`, which should install the prerequisite packages in the kernel where the notebook is running. For example, in https://github.com/elyra-ai/examples/blob/master/pipelines/hello_world/Part%201%20-%20Data%20Cleaning.ipynb
> 
> ![image](https://user-images.githubusercontent.com/13068832/108268476-6bb7d000-7121-11eb-81ce-15d03aba6c5f.png)
> 
> In what kind of environment are you running?

I'm running on
- macOS 11.2.1
- Darwin Kernel Version 20.3.0 x86_64
- Python 3.9.1
- pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

One problem in my environment for the command `!pip install PyGithub pandas` is that I do NOT have `pip` available. Instead, I have `pip3`.

If I change the command to `!pip3 install PyGithub pandas > /dev/null 2>&1`, then I don't see the problem.

**Comment by ptitzler** [comment]
Excellent! It appears that in your environment there is no `pip` symlink defined for `pip3`. We ran into a similar problem in the context of a completely different issue. To solve the problem for everyone we need to update all tutorial notebooks in https://github.com/elyra-ai/examples/tree/master/pipelines to use `pip3` instead of `pip`, because that command is always available in a Python 3 environment.

Would you be interested in making those changes and creating a pull request?

The easiest and fastest way to apply such a change _without any side effects_ would be to open every `.ipynb` file with a text editor and perform a global replace of  `!pip install` with `!pip3 install`.

**Comment by xuanyuwang** [comment]
> Excellent! It appears that in your environment there is no `pip` symlink defined for `pip3`. We ran into a similar problem in the context of a completely different issue. To solve the problem for everyone we need to update all tutorial notebooks in https://github.com/elyra-ai/examples/tree/master/pipelines to use `pip3` instead of `pip`, because that command is always available in a Python 3 environment.
> 
> Would you be interested in making those changes and creating a pull request?
> 
> The easiest and fastest way to apply such a change _without any side effects_ would be to open every `.ipynb` file with a text editor and perform a global replace of `!pip install` with `!pip3 install`.

Sure I'd like to make a pull request. I'll let you know when the PR is ready.
